import type {
  AgentWorktree,
  BranchWorkstream,
  NoCodeDevRequest,
  PullRequestReview,
  ReviewPriorityLevel,
} from "@/lib/code-review-system";

export const reviewSystem = {
  repository: "clapboard",
  mainBranch: "main",
  pmOwner: "PM / main 管理者",
  reviewModel: "Codex CLI標準モデル",
  codexModelId: "default",
  codexReviewCommand:
    'npm run review:codex -- --base main --title "main へのマージ前レビュー"',
  priorityLevels: [
    {
      priority: "crucial",
      rank: 1,
      label: "Crucial",
      owner: "PR作成者",
      mergeRule: "未対応ならマージ不可",
      body: "本番障害、データ破損、セキュリティ事故、明確な機能停止につながる指摘。",
    },
    {
      priority: "high",
      rank: 2,
      label: "High Priority",
      owner: "PR作成者",
      mergeRule: "原則マージ前に対応",
      body: "主要導線の回帰、仕様逸脱、テスト不足など、PM承認前に潰すべき指摘。",
    },
    {
      priority: "medium",
      rank: 3,
      label: "Medium",
      owner: "PM判断",
      mergeRule: "必要なら後続Issue化",
      body: "品質改善、境界条件、保守性など、リスクを明示して後続対応に回せる指摘。",
    },
    {
      priority: "low",
      rank: 4,
      label: "Low",
      owner: "PM判断",
      mergeRule: "任意対応",
      body: "軽微な表記、読みやすさ、将来の改善案。PR作成者への必須対応にはしない。",
    },
  ] satisfies ReviewPriorityLevel[],
  policies: [
    {
      id: "main-lock",
      title: "main はPM承認のみ",
      value: "direct push 0件",
      body: "AIエージェントの作業もmainへ直接入れず、Webワークツリー、PR、PM承認をマージ条件にする。",
    },
    {
      id: "branch-split",
      title: "Webワークツリー単位で分離",
      value: "1依頼 = 1WT",
      body: "自然言語やGitHub Issueの依頼を1つのWebワークツリーに閉じ、ブランチ、プレビュー、PR候補を追えるようにする。",
    },
    {
      id: "codex-review",
      title: "OAuth runnerでAI実行",
      value: "ChatGPT/OAuth",
      body: "APIキーではなくChatGPT/OAuthログイン済みのCodex CLIをrunnerとして使い、実装とレビュー材料を生成する。",
    },
    {
      id: "author-response",
      title: "PMがブラウザで承認",
      value: "PM gate",
      body: "PMはプレビュー、差分、レビュー指摘、残リスクを見て、承認、追加指示、保留を判断する。",
    },
  ],
  pipeline: [
    {
      id: "intake",
      title: "依頼受付",
      body: "自然言語、GitHub Issue、レビュー結果をノーコード依頼として受け付ける。",
    },
    {
      id: "branch",
      title: "Webワークツリー化",
      body: "1依頼を1つの作業ブランチ、プレビュー、PR候補として管制対象にする。",
    },
    {
      id: "pull-request",
      title: "AI実行",
      body: "ChatGPT/OAuthログイン済みのCodex runnerが実装、検証、PR下書きを進める。",
    },
    {
      id: "codex-review",
      title: "Codex Review",
      body: "CodexレビューでCrucial / High Priorityを抽出し、マージ前の必須対応にする。",
    },
    {
      id: "pm-merge",
      title: "PM承認",
      body: "PMがブラウザ上で承認、追加指示、保留を判断し、PR経由でmainへ入れる。",
    },
  ],
  agentWorktrees: [
    {
      id: "wt-no-code-board",
      title: "ノーコード依頼ボード",
      repository: "ymt-systems/clapboard",
      branch: "codex/no-code-worktree-board",
      base: "main",
      status: "preview-ready",
      mode: "prompt-to-branch",
      previewUrl: "/code-review?preview=wt-no-code-board",
      pullRequest: "draft",
      currentStep:
        "ブラウザ入力から作業ブランチを生成し、画面プレビューをPM確認待ちにする。",
      nextAction: "PMがプレビューを確認し、差分レビュー投入か追加指示を選ぶ。",
      humanAction: "承認 / 追加指示",
      updatedAt: "2026-04-25T20:40:00+09:00",
    },
    {
      id: "wt-github-issue",
      title: "GitHub Issueから修正PR化",
      repository: "ymt-systems/clapboard",
      branch: "codex/issue-28-mobile-review",
      base: "main",
      status: "building",
      mode: "issue-to-pr",
      previewUrl: "/code-review?preview=wt-github-issue",
      pullRequest: "未作成",
      currentStep: "Issue本文と関連差分を読み、モバイル表示の修正候補を作業中。",
      nextAction: "AIがlintと表示確認結果を添えてPR下書きを作成する。",
      humanAction: "待機",
      updatedAt: "2026-04-25T20:15:00+09:00",
    },
    {
      id: "wt-figma-ui",
      title: "Figma指示からUI反映",
      repository: "ymt-systems/clapboard",
      branch: "codex/figma-agent-panel",
      base: "main",
      status: "queued",
      mode: "design-to-ui",
      previewUrl: "/code-review?preview=wt-figma-ui",
      pullRequest: "未作成",
      currentStep: "対象画面と反映範囲を整理し、作業ブランチ作成待ち。",
      nextAction: "デザイン差分を小さなUI変更に分解してAIに投入する。",
      humanAction: "範囲確定",
      updatedAt: "2026-04-25T19:50:00+09:00",
    },
  ] satisfies AgentWorktree[],
  noCodeRequests: [
    {
      id: "req-web-intake",
      title: "Webから自然言語で実装依頼",
      requester: "PM",
      source: "ブラウザ入力",
      targetRepository: "ymt-systems/clapboard",
      status: "ready",
      expectedOutcome:
        "依頼内容から作業ブランチ、プレビュー、PR下書きまでを自動生成する。",
      agentPrompt: "ターミナルなしで依頼を受け、必要な差分と検証結果をWebに返す。",
    },
    {
      id: "req-github-issue",
      title: "GitHub IssueをAI作業に変換",
      requester: "Tech Lead",
      source: "GitHub Issue",
      targetRepository: "ymt-systems/clapboard",
      status: "building",
      expectedOutcome: "Issueを読み、再現条件、修正差分、PR本文を生成する。",
      agentPrompt: "Issue本文を仕様として扱い、mainから作業ブランチを切って修正する。",
    },
    {
      id: "req-review-gate",
      title: "PRレビュー結果をPM判断に変換",
      requester: "PM",
      source: "Codex Review",
      targetRepository: "ymt-systems/clapboard",
      status: "scoped",
      expectedOutcome:
        "Crucial / High Priorityを作成者対応、Medium以下をPM判断に分ける。",
      agentPrompt:
        "レビューコメントを優先度順に整理し、マージ可否と残リスクを要約する。",
    },
  ] satisfies NoCodeDevRequest[],
  branches: [
    {
      id: "progress-rebrand",
      title: "進捗管理リブランド",
      branch: "codex/progress-management-rebrand",
      base: "main",
      owner: "PM + Codex",
      status: "review-ready",
      pullRequest: "PR-12",
      dueAt: "2026-04-25T18:00:00+09:00",
      risk: "medium",
      nextAction: "Codexレビューを投入し、UI回帰とビルド結果を確認する。",
    },
    {
      id: "drive-sync",
      title: "Google Drive連携設計",
      branch: "codex/drive-sync-planning",
      base: "main",
      owner: "AI Agent Team",
      status: "design",
      pullRequest: "未作成",
      dueAt: "2026-04-27T12:00:00+09:00",
      risk: "low",
      nextAction: "API接続範囲と権限モデルを分けて設計PRにする。",
    },
    {
      id: "review-automation",
      title: "PRレビュー自動投入",
      branch: "codex/codex-review-gate",
      base: "main",
      owner: "PM",
      status: "implementing",
      pullRequest: "draft",
      dueAt: "2026-04-26T15:00:00+09:00",
      risk: "high",
      nextAction: "PR作成時の実行手順と失敗時のPM判断ルールを確定する。",
    },
  ] satisfies BranchWorkstream[],
  pullRequests: [
    {
      id: "pr-12",
      title: "進捗管理UIのリブランド",
      branch: "codex/progress-management-rebrand",
      base: "main",
      author: "Codex",
      reviewState: "queued",
      gate: "blocked",
      changedFiles: 17,
      riskAreas: ["UI表示崩れ", "モックデータ整合性", "Next.js build", "review wrapper"],
      comments: [
        {
          id: "c-12-1",
          priority: "high",
          status: "open",
          title: "レスポンシブ崩れの確認が不足",
          body: "新しい管制画面は横幅の狭い状態でカード密度が高いため、PR作成者が表示確認を行う。",
        },
        {
          id: "c-12-2",
          priority: "medium",
          status: "open",
          title: "レビューキューの並び順",
          body: "未対応の高優先度コメントを上に出す改善は後続Issue化でよい。",
        },
      ],
      codexCommand:
        'npm run review:codex -- --base main --title "進捗管理UIのリブランド"',
    },
    {
      id: "pr-13",
      title: "Drive URL管理の接続準備",
      branch: "codex/drive-sync-planning",
      base: "main",
      author: "AI Agent Team",
      reviewState: "needs-fix",
      gate: "blocked",
      changedFiles: 5,
      riskAreas: ["認証境界", "外部URL表示", "エラー時の退避"],
      comments: [
        {
          id: "c-13-1",
          priority: "crucial",
          status: "open",
          title: "Drive認証の失敗時動作が未定義",
          body: "認証失敗時にURLや権限情報が誤表示される可能性があるため、PR作成者がマージ前に修正する。",
        },
        {
          id: "c-13-2",
          priority: "high",
          status: "open",
          title: "外部URLの検証が不足",
          body: "不正URLを保存しないための検証ルールを追加する。",
        },
      ],
      codexCommand:
        'npm run review:codex -- --base main --title "Drive URL管理の接続準備"',
    },
    {
      id: "pr-14",
      title: "議事録テンプレート改善",
      branch: "codex/minutes-template-review",
      base: "main",
      author: "Codex",
      reviewState: "passed",
      gate: "ready",
      changedFiles: 3,
      riskAreas: ["文言回帰", "Markdown表示"],
      comments: [
        {
          id: "c-14-1",
          priority: "low",
          status: "accepted-risk",
          title: "テンプレート文言の微調整",
          body: "運用開始後の利用者フィードバックに合わせて調整する。",
        },
        {
          id: "c-14-2",
          priority: "high",
          status: "fixed",
          title: "Markdown見出しの表示回帰",
          body: "PR作成者が修正済み。再レビューで通過。",
        },
      ],
      codexCommand:
        'npm run review:codex -- --base main --title "議事録テンプレート改善"',
    },
  ] satisfies PullRequestReview[],
  checklist: [
    "Webワークツリーが1つの目的に閉じている",
    "依頼者がターミナルなしで現在状態を理解できる",
    "PR本文にPM判断用の要約、検証、残リスクがある",
    "Codex CLIがChatGPT/OAuthログイン済み",
    "CodexレビューのCrucial / High PriorityがPR作成者により対応済み",
    "CI、型チェック、ビルドのいずれかで最低限の検証が通っている",
    "PMがリリース順序と依存PRを確認している",
  ],
};
